
export const READING_CATEGORIES = {
  ANIMALS: [
    { word: "DOG", combo: ["D", "O", "G"], image: "🐶" },
    { word: "PIG", combo: ["P", "I", "G"], image: "🐷" },
    { word: "LION", combo: ["L", "I", "O", "N"], image: "🦁" },
    { word: "BIRD", combo: ["B", "I", "R", "D"], image: "🐦" },
    { word: "COW", combo: ["C", "O", "W"], image: "🐮" },
    { word: "HORSE", combo: ["H", "O", "R", "S", "E"], image: "🐴" },
    { word: "SHEEP", combo: ["S", "H", "E", "E", "P"], image: "🐑" },
    { word: "DUCK", combo: ["D", "U", "C", "K"], image: "🦆" },
    { word: "HEN", combo: ["H", "E", "N"], image: "🐔" },
    { word: "BEAR", combo: ["B", "E", "A", "R"], image: "🐻" },
    { word: "WOLF", combo: ["W", "O", "L", "F"], image: "🐺" },
    { word: "FOX", combo: ["F", "O", "X"], image: "🦊" },
    { word: "DEER", combo: ["D", "E", "E", "R"], image: "🦌" },
    { word: "FROG", combo: ["F", "R", "O", "G"], image: "🐸" },
    { word: "FISH", combo: ["F", "I", "S", "H"], image: "🐟" },
    { word: "BEE", combo: ["B", "E", "E"], image: "🐝" },
    { word: "ANT", combo: ["A", "N", "T"], image: "🐜" },
    { word: "BAT", combo: ["B", "A", "T"], image: "🦇" },
    { word: "RAT", combo: ["R", "A", "T"], image: "🐀" },
    { word: "OWL", combo: ["O", "W", "L"], image: "🦉" },
    { word: "SEAL", combo: ["S", "E", "A", "L"], image: "🦭" },
    { word: "CRAB", combo: ["C", "R", "A", "B"], image: "🦀" },
    { word: "WHALE", combo: ["W", "H", "A", "L", "E"], image: "🐋" },
    { word: "SHARK", combo: ["S", "H", "A", "R", "K"], image: "🦈" },
    { word: "SNAKE", combo: ["S", "N", "A", "K", "E"], image: "🐍" },
    { word: "TIGER", combo: ["T", "I", "G", "E", "R"], image: "🐯" },
    { word: "ZEBRA", combo: ["Z", "E", "B", "R", "A"], image: "🦓" },
    { word: "MONKEY", combo: ["M", "O", "N", "K", "E", "Y"], image: "🐒" },
    { word: "HIPPO", combo: ["H", "I", "P", "P", "O"], image: "🦛" },
  ],
  FRUITS: [
    { word: "APPLE", combo: ["A", "P", "P", "L", "E"], image: "🍎" },
    { word: "PEAR", combo: ["P", "E", "A", "R"], image: "🍐" },
    { word: "PLUM", combo: ["P", "L", "U", "M"], image: "🍑" },
    { word: "KIWI", combo: ["K", "I", "W", "I"], image: "🥝" },
    { word: "FIG", combo: ["F", "I", "G"], image: "🍈" },
    { word: "GRAPE", combo: ["G", "R", "A", "P", "E"], image: "🍇" },
    { word: "PEACH", combo: ["P", "E", "A", "C", "H"], image: "🍑" },
    { word: "MELON", combo: ["M", "E", "L", "O", "N"], image: "🍉" },
    { word: "BERRY", combo: ["B", "E", "R", "R", "Y"], image: "🍓" },
    { word: "LIME", combo: ["L", "I", "M", "E"], image: "🍋" },
    { word: "DATE", combo: ["D", "A", "T", "E"], image: "🌴" },
    { word: "NUT", combo: ["N", "U", "T"], image: "🥜" },
    { word: "CHERRY", combo: ["C", "H", "E", "R", "R", "Y"], image: "🍒" },
    { word: "MANGO", combo: ["M", "A", "N", "G", "O"], image: "🥭" },
    { word: "GUAVA", combo: ["G", "U", "A", "V", "A"], image: "🍈" },
    { word: "OLIVE", combo: ["O", "L", "I", "V", "E"], image: "🫒" },
    { word: "ORANGE", combo: ["O", "R", "A", "N", "G", "E"], image: "🍊" },
    { word: "BANANA", combo: ["B", "A", "N", "A", "N", "A"], image: "🍌" },
    { word: "LEMON", combo: ["L", "E", "M", "O", "N"], image: "🍋" },
    { word: "ANANAS", combo: ["A", "N", "A", "N", "A", "S"], image: "🍍" },
    { word: "TOMATO", combo: ["T", "O", "M", "A", "T", "O"], image: "🍅" },
    { word: "CORN", combo: ["C", "O", "R", "N"], image: "🌽" },
    { word: "PEA", combo: ["P", "E", "A"], image: "🫛" },
    { word: "BEAN", combo: ["B", "E", "A", "N"], image: "🫘" },
    { word: "CHILI", combo: ["C", "H", "I", "L", "I"], image: "🌶️" },
    { word: "ONION", combo: ["O", "N", "I", "O", "N"], image: "🧅" },
    { word: "POTATO", combo: ["P", "O", "T", "A", "T", "O"], image: "🥔" },
    { word: "BREAD", combo: ["B", "R", "E", "A", "D"], image: "🍞" },
    { word: "CAKE", combo: ["C", "A", "K", "E"], image: "🍰" },
    { word: "EGG", combo: ["E", "G", "G"], image: "🥚" },
  ],
  SCHOOL: [
    { word: "PEN", combo: ["P", "E", "N"], image: "🖊️" },
    { word: "BOOK", combo: ["B", "O", "O", "K"], image: "📖" },
    { word: "DESK", combo: ["D", "E", "S", "K"], image: "🪑" },
    { word: "PAGE", combo: ["P", "A", "G", "E"], image: "📄" },
    { word: "BELL", combo: ["B", "E", "L", "L"], image: "🔔" },
    { word: "BAG", combo: ["B", "A", "G"], image: "🎒" },
    { word: "GLUE", combo: ["G", "L", "U", "E"], image: "🧪" },
    { word: "TAPE", combo: ["T", "A", "P", "E"], image: "🎞️" },
    { word: "INK", combo: ["I", "N", "K"], image: "🖋️" },
    { word: "MAP", combo: ["M", "A", "P"], image: "🗺️" },
    { word: "GLOBE", combo: ["G", "L", "O", "B", "E"], image: "🌍" },
    { word: "MATH", combo: ["M", "A", "T", "H"], image: "➕" },
    { word: "ART", combo: ["A", "R", "T"], image: "🎨" },
    { word: "SONG", combo: ["S", "O", "N", "G"], image: "🎵" },
    { word: "READ", combo: ["R", "E", "A", "D"], image: "📚" },
    { word: "DRAW", combo: ["D", "R", "A", "W"], image: "✏️" },
    { word: "NOTE", combo: ["N", "O", "T", "E"], image: "📝" },
    { word: "CLASS", combo: ["C", "L", "A", "S", "S"], image: "🏫" },
    { word: "CHAIR", combo: ["C", "H", "A", "I", "R"], image: "🪑" },
    { word: "FLOOR", combo: ["F", "L", "O", "O", "R"], image: "🛹" },
    { word: "DOOR", combo: ["D", "O", "O", "R"], image: "🚪" },
    { word: "WALL", combo: ["W", "A", "L", "L"], image: "🧱" },
    { word: "CLOCK", combo: ["C", "L", "O", "C", "K"], image: "⏰" },
    { word: "TEST", combo: ["T", "E", "S", "T"], image: "📄" },
    { word: "MARK", combo: ["M", "A", "R", "K"], image: "✔️" },
    { word: "RULER", combo: ["R", "U", "L", "E", "R"], image: "📏" },
    { word: "CHALK", combo: ["C", "H", "A", "L", "K"], image: "🖍️" },
    { word: "BOARD", combo: ["B", "O", "A", "R", "D"], image: "📋" },
    { word: "STUDY", combo: ["S", "T", "U", "D", "Y"], image: "📖" },
    { word: "LEARN", combo: ["L", "E", "A", "R", "N"], image: "💡" },
  ],
  PLAYGROUND: [
    { word: "SLIDE", combo: ["S", "L", "I", "D", "E"], image: "🛝" },
    { word: "SWING", combo: ["S", "W", "I", "N", "G"], image: "🎠" },
    { word: "BAT", combo: ["B", "A", "T"], image: "🏏" },
    { word: "BALL", combo: ["B", "A", "L", "L"], image: "⚽" },
    { word: "RUN", combo: ["R", "U", "N"], image: "🏃" },
    { word: "JUMP", combo: ["J", "U", "M", "P"], image: "🦘" },
    { word: "HOP", combo: ["H", "O", "P"], image: "🐰" },
    { word: "SKIP", combo: ["S", "K", "I", "P"], image: "🪢" },
    { word: "PLAY", combo: ["P", "L", "A", "Y"], image: "🧸" },
    { word: "FUN", combo: ["F", "U", "N"], image: "😄" },
    { word: "PARK", combo: ["P", "A", "R", "K"], image: "🌳" },
    { word: "SAND", combo: ["S", "A", "N", "D"], image: "🏖️" },
    { word: "NET", combo: ["N", "E", "T"], image: "🕸️" },
    { word: "GOAL", combo: ["G", "O", "A", "L"], image: "🥅" },
    { word: "WIN", combo: ["W", "I", "N"], image: "🏆" },
    { word: "LOSE", combo: ["L", "O", "S", "E"], image: "😢" },
    { word: "TEAM", combo: ["T", "E", "A", "M"], image: "🤝" },
    { word: "SPORT", combo: ["S", "P", "O", "R", "T"], image: "🏅" },
    { word: "RACE", combo: ["R", "A", "C", "E"], image: "🏁" },
    { word: "FAST", combo: ["F", "A", "S", "T"], image: "⚡" },
    { word: "SLOW", combo: ["S", "L", "O", "W"], image: "🐌" },
    { word: "UP", combo: ["U", "P"], image: "⬆️" },
    { word: "DOWN", combo: ["D", "O", "W", "N"], image: "⬇️" },
    { word: "HIGH", combo: ["H", "I", "G", "H"], image: "☁️" },
    { word: "LOW", combo: ["L", "O", "W"], image: "🌱" },
    { word: "KICK", combo: ["K", "I", "C", "K"], image: "🦵" },
    { word: "TOSS", combo: ["T", "O", "S", "S"], image: "⚾" },
    { word: "CATCH", combo: ["C", "A", "T", "C", "H"], image: "🧤" },
    { word: "SPIN", combo: ["S", "P", "I", "N"], image: "🌀" },
    { word: "CLIMB", combo: ["C", "L", "I", "M", "B"], image: "🧗" },
  ],
  TOYS: [
    { word: "DOLL", combo: ["D", "O", "L", "L"], image: "🪆" },
    { word: "TOY", combo: ["T", "O", "Y"], image: "🧸" },
    { word: "CAR", combo: ["C", "A", "R"], image: "🚗" },
    { word: "BALL", combo: ["B", "A", "L", "L"], image: "🏀" },
    { word: "KITE", combo: ["K", "I", "T", "E"], image: "🪁" },
    { word: "YOYO", combo: ["Y", "O", "Y", "O"], image: "🪀" },
    { word: "BLOCK", combo: ["B", "L", "O", "C", "K"], image: "🧱" },
    { word: "TRAIN", combo: ["T", "R", "A", "I", "N"], image: "🚂" },
    { word: "PLANE", combo: ["P", "L", "A", "N", "E"], image: "✈️" },
    { word: "BOAT", combo: ["B", "O", "A", "T"], image: "⛵" },
    { word: "ROBOT", combo: ["R", "O", "B", "O", "T"], image: "🤖" },
    { word: "GAME", combo: ["G", "A", "M", "E"], image: "🎮" },
    { word: "CARD", combo: ["C", "A", "R", "D"], image: "🃏" },
    { word: "DICE", combo: ["D", "I", "C", "E"], image: "🎲" },
    { word: "BIKE", combo: ["B", "I", "K", "E"], image: "🚲" },
    { word: "DRUM", combo: ["D", "R", "U", "M"], image: "🥁" },
    { word: "HORN", combo: ["H", "O", "R", "N"], image: "📯" },
    { word: "FLAG", combo: ["F", "L", "A", "G"], image: "🚩" },
    { word: "CAPE", combo: ["C", "A", "P", "E"], image: "🧥" },
    { word: "MASK", combo: ["M", "A", "S", "K"], image: "🎭" },
    { word: "WAND", combo: ["W", "A", "N", "D"], image: "🪄" },
    { word: "BEAR", combo: ["B", "E", "A", "R"], image: "🧸" },
    { word: "PET", combo: ["P", "E", "T"], image: "🐶" },
    { word: "BOX", combo: ["B", "O", "X"], image: "📦" },
    { word: "LID", combo: ["L", "I", "D"], image: "🧢" },
    { word: "GIFT", combo: ["G", "I", "F", "T"], image: "🎁" },
    { word: "TRUCK", combo: ["T", "R", "U", "C", "K"], image: "🚚" },
    { word: "PUZZLE", combo: ["P", "U", "Z", "Z", "L", "E"], image: "🧩" },
    { word: "SLIME", combo: ["S", "L", "I", "M", "E"], image: "🧪" },
    { word: "CLAY", combo: ["C", "L", "A", "Y"], image: "🎨" },
  ],
  PLANTS: [
    { word: "TREE", combo: ["T", "R", "E", "E"], image: "🌳" },
    { word: "LEAF", combo: ["L", "E", "A", "F"], image: "🍃" },
    { word: "ROOT", combo: ["R", "O", "O", "T"], image: "🥕" },
    { word: "STEM", combo: ["S", "T", "E", "M"], image: "🌿" },
    { word: "SEED", combo: ["S", "E", "E", "D"], image: "🌱" },
    { word: "ROSE", combo: ["R", "O", "S", "E"], image: "🌹" },
    { word: "FERN", combo: ["F", "E", "R", "N"], image: "🌿" },
    { word: "MOSS", combo: ["M", "O", "S", "S"], image: "🍃" },
    { word: "WEED", combo: ["W", "E", "E", "D"], image: "🌱" },
    { word: "BUD", combo: ["B", "U", "D"], image: "🌸" },
    { word: "BLOOM", combo: ["B", "L", "O", "O", "M"], image: "🌼" },
    { word: "SOIL", combo: ["S", "O", "I", "L"], image: "🪴" },
    { word: "DIRT", combo: ["D", "I", "R", "T"], image: "🟫" },
    { word: "MUD", combo: ["M", "U", "D"], image: "💩" },
    { word: "POT", combo: ["P", "O", "T"], image: "🪴" },
    { word: "YARD", combo: ["Y", "A", "R", "D"], image: "🏡" },
    { word: "LAWN", combo: ["L", "A", "W", "N"], image: "🎋" },
    { word: "BUSH", combo: ["B", "U", "S", "H"], image: "🌳" },
    { word: "VINE", combo: ["V", "I", "N", "E"], image: "🌿" },
    { word: "PINE", combo: ["P", "I", "N", "E"], image: "🌲" },
    { word: "OAK", combo: ["O", "A", "K"], image: "🌳" },
    { word: "PALM", combo: ["P", "A", "L", "M"], image: "🌴" },
    { word: "BARK", combo: ["B", "A", "R", "K"], image: "🪵" },
    { word: "WOOD", combo: ["W", "O", "O", "D"], image: "🪵" },
    { word: "GRASS", combo: ["G", "R", "A", "S", "S"], image: "🌱" },
    { word: "FIELD", combo: ["F", "I", "E", "L", "D"], image: "🏞️" },
    { word: "FLOWER", combo: ["F", "L", "O", "W", "E", "R"], image: "🌻" },
    { word: "BAMBOO", combo: ["B", "A", "M", "B", "O", "O"], image: "🎍" },
    { word: "CACTUS", combo: ["C", "A", "C", "T", "U", "S"], image: "🌵" },
    { word: "LILY", combo: ["L", "I", "L", "Y"], image: "🪷" },
  ],
  BODY: [
    { word: "EYE", combo: ["E", "Y", "E"], image: "👁️" },
    { word: "NOSE", combo: ["N", "O", "S", "E"], image: "👃" },
    { word: "HAND", combo: ["H", "A", "N", "D"], image: "🖐️" },
    { word: "FOOT", combo: ["F", "O", "O", "T"], image: "🦶" },
    { word: "EAR", combo: ["E", "A", "R"], image: "👂" },
    { word: "MOUTH", combo: ["M", "O", "U", "T", "H"], image: "👄" },
    { word: "ARM", combo: ["A", "R", "M"], image: "💪" },
    { word: "LEG", combo: ["L", "E", "G"], image: "🦵" },
    { word: "HEAD", combo: ["H", "E", "A", "D"], image: "👤" },
    { word: "HAIR", combo: ["H", "A", "I", "R"], image: "💇" },
    { word: "FACE", combo: ["F", "A", "C", "E"], image: "😊" },
    { word: "NECK", combo: ["N", "E", "C", "K"], image: "🧣" },
    { word: "BACK", combo: ["B", "A", "C", "K"], image: "🎒" },
    { word: "KNEE", combo: ["K", "N", "E", "E"], image: "🦵" },
    { word: "TOE", combo: ["T", "O", "E"], image: "🦶" },
    { word: "LIP", combo: ["L", "I", "P"], image: "👄" },
    { word: "TOOTH", combo: ["T", "O", "O", "T", "H"], image: "🦷" },
    { word: "GUM", combo: ["G", "U", "M"], image: "🦷" },
    { word: "CHIN", combo: ["C", "H", "I", "N"], image: "😊" },
    { word: "CHEEK", combo: ["C", "H", "E", "E", "K"], image: "😊" },
    { word: "BROW", combo: ["B", "R", "O", "W"], image: "🤨" },
    { word: "NAIL", combo: ["N", "A", "I", "L"], image: "💅" },
    { word: "SKIN", combo: ["S", "K", "I", "N"], image: "🖐️" },
    { word: "BONE", combo: ["B", "O", "N", "E"], image: "🦴" },
    { word: "HEART", combo: ["H", "E", "A", "R", "T"], image: "❤️" },
    { word: "LUNG", combo: ["L", "U", "N", "G"], image: "🫁" },
    { word: "STOMACH", combo: ["S", "T", "O", "M", "A", "C", "H"], image: "🤰" },
    { word: "FIST", combo: ["F", "I", "S", "T"], image: "✊" },
    { word: "PALM", combo: ["P", "A", "L", "M"], image: "✋" },
    { word: "HEEL", combo: ["H", "E", "E", "L"], image: "🦶" },
  ],
  FAMILY: [
    { word: "MOM", combo: ["M", "O", "M"], image: "🤱" },
    { word: "DAD", combo: ["D", "A", "D"], image: "👨" },
    { word: "BABY", combo: ["B", "A", "B", "Y"], image: "👶" },
    { word: "GIRL", combo: ["G", "I", "R", "L"], image: "👧" },
    { word: "BOY", combo: ["B", "O", "Y"], image: "👦" },
    { word: "NAN", combo: ["N", "A", "N"], image: "👵" },
    { word: "GRAN", combo: ["G", "R", "A", "N"], image: "👵" },
    { word: "AUNT", combo: ["A", "U", "N", "T"], image: "👩" },
    { word: "SON", combo: ["S", "O", "N"], image: "👦" },
    { word: "SISTER", combo: ["S", "I", "S", "T", "E", "R"], image: "👧" },
    { word: "BRO", combo: ["B", "R", "O"], image: "👦" },
    { word: "KID", combo: ["K", "I", "D"], image: "🧒" },
    { word: "KIN", combo: ["K", "I", "N"], image: "👨‍👩‍👧‍👦" },
    { word: "MAN", combo: ["M", "A", "N"], image: "👨" },
    { word: "WIFE", combo: ["W", "I", "F", "E"], image: "👩" },
    { word: "PA", combo: ["P", "A"], image: "👨" },
    { word: "MA", combo: ["M", "A"], image: "👩" },
    { word: "CHILD", combo: ["C", "H", "I", "L", "D"], image: "🧒" },
    { word: "TWIN", combo: ["T", "W", "I", "N"], image: "👯" },
    { word: "NAME", combo: ["N", "A", "M", "E"], image: "🏷️" },
    { word: "HOME", combo: ["H", "O", "M", "E"], image: "🏠" },
    { word: "LOVE", combo: ["L", "O", "V", "E"], image: "❤️" },
    { word: "HUG", combo: ["H", "U", "G"], image: "🫂" },
    { word: "KISS", combo: ["K", "I", "S", "S"], image: "💋" },
    { word: "HELP", combo: ["H", "E", "L", "P"], image: "🤝" },
    { word: "SHARE", combo: ["S", "H", "A", "R", "E"], image: "🤲" },
    { word: "PLAY", combo: ["P", "L", "A", "Y"], image: "🧸" },
    { word: "CARE", combo: ["C", "A", "R", "E"], image: "🧡" },
    { word: "KIND", combo: ["K", "I", "N", "D"], image: "😇" },
    { word: "NICE", combo: ["N", "I", "C", "E"], image: "👍" },
  ],
  WEATHER: [
    { word: "SUN", combo: ["S", "U", "N"], image: "☀️" },
    { word: "RAIN", combo: ["R", "A", "I", "N"], image: "🌧️" },
    { word: "SNOW", combo: ["S", "N", "O", "W"], image: "❄️" },
    { word: "WIND", combo: ["W", "I", "N", "D"], image: "💨" },
    { word: "HOT", combo: ["H", "O", "T"], image: "🔥" },
    { word: "COLD", combo: ["C", "O", "L", "D"], image: "🧊" },
    { word: "WET", combo: ["W", "E", "T"], image: "💧" },
    { word: "DRY", combo: ["D", "R", "Y"], image: "🌵" },
    { word: "FOG", combo: ["F", "O", "G"], image: "🌫️" },
    { word: "MIST", combo: ["M", "I", "S", "T"], image: "🌫️" },
    { word: "STORM", combo: ["S", "T", "O", "R", "M"], image: "⛈️" },
    { word: "CLOUD", combo: ["C", "L", "O", "U", "D"], image: "☁️" },
    { word: "SKY", combo: ["S", "K", "Y"], image: "🌌" },
    { word: "MOON", combo: ["M", "O", "O", "N"], image: "🌙" },
    { word: "STAR", combo: ["S", "T", "A", "R"], image: "⭐" },
    { word: "DAY", combo: ["D", "A", "Y"], image: "☀️" },
    { word: "NIGHT", combo: ["N", "I", "G", "H", "T"], image: "🌙" },
    { word: "ICE", combo: ["I", "C", "E"], image: "🧊" },
    { word: "HEAT", combo: ["H", "E", "A", "T"], image: "🔥" },
    { word: "DEW", combo: ["D", "E", "W"], image: "💧" },
    { word: "BOLT", combo: ["B", "O", "L", "T"], image: "⚡" },
    { word: "FLASH", combo: ["F", "L", "A", "S", "H"], image: "⚡" },
    { word: "SHADE", combo: ["S", "H", "A", "D", "E"], image: "⛱️" },
    { word: "FROST", combo: ["F", "R", "O", "S", "T"], image: "❄️" },
    { word: "BREEZE", combo: ["B", "R", "E", "E", "Z", "E"], image: "🍃" },
    { word: "CHILL", combo: ["C", "H", "I", "L", "L"], image: "🥶" },
    { word: "THUNDER", combo: ["T", "H", "U", "N", "D", "E", "R"], image: "🌩️" },
    { word: "RAINBOW", combo: ["R", "A", "I", "N", "B", "O", "W"], image: "🌈" },
    { word: "LIGHT", combo: ["L", "I", "G", "H", "T"], image: "💡" },
    { word: "DARK", combo: ["D", "A", "R", "K"], image: "🌑" },
  ],
  EVERYDAY: [
    { word: "BUS", combo: ["B", "U", "S"], image: "🚌" },
    { word: "PARK", combo: ["P", "A", "R", "K"], image: "🌳" },
    { word: "BED", combo: ["B", "E", "D"], image: "🛏️" },
    { word: "CUP", combo: ["C", "U", "P"], image: "🥤" },
    { word: "BOOK", combo: ["B", "O", "O", "K"], image: "📖" },
    { word: "PEN", combo: ["P", "E", "N"], image: "🖊️" },
    { word: "BAG", combo: ["B", "A", "G"], image: "🎒" },
    { word: "CAR", combo: ["C", "A", "R"], image: "🚗" },
    { word: "VAN", combo: ["V", "A", "N"], image: "🚐" },
    { word: "BOX", combo: ["B", "O", "X"], image: "📦" },
    { word: "KEY", combo: ["K", "E", "Y"], image: "🔑" },
    { word: "DOOR", combo: ["D", "O", "O", "R"], image: "🚪" },
    { word: "WALL", combo: ["W", "A", "L", "L"], image: "🧱" },
    { word: "FLOOR", combo: ["F", "L", "O", "O", "R"], image: "🛹" },
    { word: "ROOF", combo: ["R", "O", "O", "F"], image: "🏠" },
    { word: "LAMP", combo: ["L", "A", "M", "P"], image: "💡" },
    { word: "DESK", combo: ["D", "E", "S", "K"], image: "🪑" },
    { word: "CHAIR", combo: ["C", "H", "A", "I", "R"], image: "🪑" },
    { word: "FORK", combo: ["F", "O", "R", "K"], image: "🍴" },
    { word: "SPOON", combo: ["S", "P", "O", "O", "N"], image: "🥄" },
    { word: "PLATE", combo: ["P", "L", "A", "T", "E"], image: "🍽️" },
    { word: "BOWL", combo: ["B", "O", "W", "L"], image: "🥣" },
    { word: "GLASS", combo: ["G", "L", "A", "S", "S"], image: "🥛" },
    { word: "SOAP", combo: ["S", "O", "A", "P"], image: "🧼" },
    { word: "TOWEL", combo: ["T", "O", "W", "E", "L"], image: "🧖" },
    { word: "BRUSH", combo: ["B", "R", "U", "S", "H"], image: "🖌️" },
    { word: "SHOE", combo: ["S", "H", "O", "E"], image: "👟" },
    { word: "SOCK", combo: ["S", "O", "C", "K"], image: "🧦" },
    { word: "COAT", combo: ["C", "O", "A", "T"], image: "🧥" },
    { word: "HAT", combo: ["H", "A", "T"], image: "👒" },
  ],
  FOODS: [
    { word: "CAKE", combo: ["C", "A", "K", "E"], image: "🍰" },
    { word: "MILK", combo: ["M", "I", "L", "K"], image: "🥛" },
    { word: "EGG", combo: ["E", "G", "G"], image: "🥚" },
    { word: "PIZZA", combo: ["P", "I", "Z", "Z", "A"], image: "🍕" },
    { word: "BREAD", combo: ["B", "R", "E", "A", "D"], image: "🍞" },
    { word: "RICE", combo: ["R", "I", "C", "E"], image: "🍚" },
    { word: "SOUP", combo: ["S", "O", "U", "P"], image: "🥣" },
    { word: "FISH", combo: ["F", "I", "S", "H"], image: "🐟" },
    { word: "MEAT", combo: ["M", "E", "A", "T"], image: "🥩" },
    { word: "HAM", combo: ["H", "A", "M"], image: "🍖" },
    { word: "JAM", combo: ["J", "A", "M"], image: "🍯" },
    { word: "BUN", combo: ["B", "U", "N"], image: "🥯" },
    { word: "PIE", combo: ["P", "I", "E"], image: "🥧" },
    { word: "CHIP", combo: ["C", "H", "I", "P"], image: "🍟" },
    { word: "TACO", combo: ["T", "A", "C", "O"], image: "🌮" },
    { word: "BEAN", combo: ["B", "E", "A", "N"], image: "🫘" },
    { word: "CORN", combo: ["C", "O", "R", "N"], image: "🌽" },
    { word: "TOAST", combo: ["T", "O", "A", "S", "T"], image: "🍞" },
    { word: "PASTA", combo: ["P", "A", "S", "T", "A"], image: "🍝" },
    { word: "SALT", combo: ["S", "A", "L", "T"], image: "🧂" },
    { word: "TEA", combo: ["T", "E", "A"], image: "🍵" },
    { word: "JUICE", combo: ["J", "U", "I", "C", "E"], image: "🧃" },
    { word: "COLA", combo: ["C", "O", "L", "A"], image: "🥤" },
    { word: "WATER", combo: ["W", "A", "T", "E", "R"], image: "🚰" },
    { word: "STEAK", combo: ["S", "T", "E", "A", "K"], image: "🥩" },
    { word: "STEW", combo: ["S", "T", "E", "W"], image: "🍲" },
    { word: "NUT", combo: ["N", "U", "T"], image: "🥜" },
    { word: "JELLY", combo: ["J", "E", "L", "L", "Y"], image: "🍮" },
    { word: "HONEY", combo: ["H", "O", "N", "E", "Y"], image: "🍯" },
    { word: "CHEESE", combo: ["C", "H", "E", "E", "S", "E"], image: "🧀" },
  ],
};
